### ISSUE TITLE
Difficulty pairing versions of the different SDK crates

### ISSUE THREAD

**Issue by jprendes** [WasmEdge/wasmedge-rust-sdk#107]
There are several crates making up `wasmedge-sdk`, and their versions are not synchronized.
So far, the version table in the README has been helpful to workaround this, but recently it's become out of sync (e.g., v0.14.0 is not on the table).
Personally, I would prefer having all the crates using the same version, synchronized with WasmEdge's version.

**Comment by L-jasmine** [comment]
I'll update the version table in th README.  thank you
