### ISSUE TITLE
Execution Timeout Milliseconds

### ISSUE THREAD

**Issue by AshantiM** [WasmEdge/wasmedge-rust-sdk#35]
Hello,

We have been using the timeout branch to test some of our guest function execution timeout code. All is well but we would  like the ability to limit by milliseconds as well. Would something like this be possible? Seconds at the moment is a bit limiting

**Comment by apepkuss** [comment]
@AshantiM We have no branch named `timeout` or similar names. Could you please share with us the link to it or your code if you don't mind? Thanks a lot!

**Comment by AshantiM** [comment]
Oh sorry thought I replied to this. This was for run_func_with_timeout on the VM

**Comment by L-jasmine** [comment]
@AshantiM Hi, actually we've already done.
https://github.com/WasmEdge/wasmedge-rust-sdk/pull/76

**Comment by apepkuss** [comment]
@AshantiM Please help close the issue if it has been fixed. Thanks a lot!
