### ISSUE TITLE
Compilation error with wasmedge-sdk 0.11.0

### ISSUE THREAD

**Issue by ashenoyxyz** [WasmEdge/wasmedge-rust-sdk#47]
Hi - I'm trying to use wasmedge-sdk 0.11.0 for a use case involving async host functions. I seem to be running into compilation issues even though I am using the appropriate version of the WasmEdge library. Could you please provide some pointers on how to resolve this or whether I am missing something obvious here?

**Following are the details -**

**Excerpt of the error**

<pre>
# cargo b
   Compiling wasmedge-sys v0.16.0
error[E0425]: cannot find function, tuple struct or tuple variant `WasmEdge_ModuleInstanceGetHostData` in module `ffi`
    --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmedge-sys-0.16.0/src/instance/module.rs:282:33
     |
282  |           let ctx = unsafe { ffi::WasmEdge_ModuleInstanceGetHostData(self.inner.lock().0) };
     |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `WasmEdge_ModuleInstanceGetModuleName`

...
...

The following warnings were emitted during compilation:

warning: [wasmedge-sys] searching for existing libwasmedge install
warning: [wasmedge-sys] searching for libwasmedge at LibWasmEdgePaths { lib_dir: "/root/.wasmedge/lib64", inc_dir: "/root/.wasmedge/include" }
warning: [wasmedge-sys] searching for libwasmedge at LibWasmEdgePaths { lib_dir: "/root/.wasmedge/lib", inc_dir: "/root/.wasmedge/include" }
warning: [wasmedge-sys] found libwasmedge at LibWasmEdgePaths { lib_dir: "/root/.wasmedge/lib", inc_dir: "/root/.wasmedge/include" }
warning: [wasmedge-sys] generating bindgen header "/root/git/wasmedge-test/target/debug/build/wasmedge-sys-171098a0daf419ed/out/wasmedge.rs"
</pre>

**Cargo.toml**

<pre>
[package]
name = "wasmedge_test"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.12", features = ["multipart"] }
tokio = { version = "1.26.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["cors"] }
wasmedge-sdk = {version = "0.11.0", features = ["async"]}
</pre>

**WasmEdge library version**

<pre>
# /root/.wasmedge/bin/wasmedge -v
/root/.wasmedge/bin/wasmedge version 0.13.3
</pre>

**Comment by apepkuss** [comment]
@ashenoyxyz Sorry for the late reply. According to the error message and the relevant info you provided above, we cannot tell what causes the failure. Could you please share with us more info about the platform you're using, like OS, version of rustc, and etc.?

In addition, to help you get familiar with how to create an `async` host function, we have an example [define-async-host-func](https://github.com/second-state/wasmedge-rustsdk-examples/tree/main/define-async-host-func) for you. The `README` shows the detailed steps to run the example, including how to deploy WasmEdge Runtime. Hope the example can help you. Thanks a lot!

**Comment by apepkuss** [comment]
@ashenoyxyz We released [WasmEdge Rust SDK 0.11.2](https://crates.io/crates/wasmedge-sdk) today. You can try your code with this new release if you have an interest in it. Thanks!
