### ISSUE TITLE
Please bump `wat` to the newest version or relex the strict version requirement

### ISSUE THREAD

**Issue by Mossaka** [WasmEdge/wasmedge-rust-sdk#88]

**Comment by apepkuss** [comment]
@Mossaka Thanks for your report. I checked `wasmtime` and `wat` crates. The latest version of `wasmtime` is `v14.0.4`, and it uses `wat` of `^1.0.77`, while the latest version of `wat` is `1.0.79`. Based on the situation above, we'll update this dep to `1.0`, is it ok for you?

**Comment by Mossaka** [comment]
Sounds good. Appreciate 🙏
